services:
  app:
    build: .
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
